const fs = require('fs');
const path = 'C:/Users/advai/OneDrive/Documents/FRONTIER-JESSIE/pr-fixer/src/lib/pipeline.ts';

// Build the file using string concatenation - NO template literals anywhere
let code = '';

code += 'import {\n';
code += '  addStage,\n';
code += '  getJob,\n';
code += '  incrementFixAttempt,\n';
code += '  setDiff,\n';
code += '  updateJobStatus,\n';
code += '  updateStage,\n';
code += '} from "./store";\n';
code += 'import type { ErrorType } from "./types";\n';
code += '\n';
code += 'const MAX_ATTEMPTS = 5;\n';
code += 'const MAX_EXECUTION_MS = 120_000;\n';
code += '\n';
code += 'const CANNED_DIFFS: Record<ErrorType, { diff: string; explanation: string }> = {\n';
code += '  lint: {\n';
code += '    diff: [\n';
code += '      "--- a/src/utils/format.ts",\n';
code += '      "+++ b/src/utils/format.ts",\n';
code += '      "@@ -15,7 +15,7 @@",\n';
code += '      "   return str.split(\\"\\").reverse().join(\\"\\").toLowerCase().trim();",\n';
code += '      " }",\n';
code += '      " ",\n';
code += '      "-export function formatDate(date: Date): string {",\n';
code += '      "+export function formatDate(date: Date): string {",\n';
code += '      "   const year = date.getFullYear();",\n';
code += '      "-  const month = String(date.getMonth() + 1).padStart(2, \\"0\\");",\n';
code += '      "-  const day = String(date.getDate()).padStart(2, \\"0\\");",\n';
code += '      "+  const month = String(date.getMonth() + 1).padStart(2, \\"0\\");",\n';
code += '      "+  const day   = String(date.getDate()).padStart(2, \\"0\\");",\n';
code += '      "   return \\u0060${year}-${month}-${day}\\u0060;",\n';
code += '      " }",\n';
code += '    ].join("\n"),\n';
code += '    explanation: "ESLint no-multi-spaces: Extra spacing before day. Removed whitespace.",\n';
code += '  },\n';
code += '  type_error: {\n';
code += '    diff: [\n';
code += '      "--- a/src/services/api.ts",\n';
code += '      "+++ b/src/services/api.ts",\n';
code += '      "@@ -42,7 +42,7 @@",\n';
code += '      " ",\n';
code += '      " interface ApiResponse<T> {",\n';
code += '      "   data: T;",\n';
code += '      "-  status: string;",\n';
code += '      "+  statusCode: number;",\n';
code += '      "   message: string;",\n';
code += '      " }",\n';
code += '      " ",\n';
code += '      "@@ -55,5 +55,5 @@",\n';
code += '      " export async function fetchUser(id: string): Promise<ApiResponse<User>> {",\n';
code += '      "   const res = await fetch(\\\"/api/users/\" + id + \"\\\");",\n';
code += '      "   const json = await res.json();",\n';
code += '      "-  return json as ApiResponse<User>;",\n';
code += '      "+  return { data: json.data, statusCode: res.status, message: json.message };",\n';
code += '      " }",\n';
code += '    ].join("\n"),\n';
code += '    explanation: "TS2322: status field expects number, got string. Fixed.",\n';
code += '  },\n';
code += '  failing_test: {\n';
code += '    diff: [\n';
code += '      "--- a/src/components/Counter.test.tsx",\n';
code += '      "+++ b/src/components/Counter.test.tsx",\n';
code += '      "@@ -10,10 +10,10 @@",\n';
code += '      "   render(<Counter initialValue={5} />);",\n';
code += '      "-  expect(screen.getByText(\\\"Count: 5\\\")).toBeInTheDocument();",\n';
code += '      "+  expect(screen.getByText(\\\"Count: 5\\\")).toBeDefined();",\n';
code += '      "   ",\n';
code += '      "   fireEvent.click(screen.getByText(\\\"Increment\\\"));",\n';
code += '      "-  expect(screen.getByText(\\\"Count: 6\\\")).toBeInTheDocument();",\n';
code += '      "+  expect(screen.getByText(\\\"Count: 6\\\")).toBeDefined();",\n';
code += '      " });",\n';
code += '      " ",\n';
code += '      " test(\\\"decrements correctly\\\", () => {",\n';
code += '      "   render(<Counter initialValue={10} />);",\n';
code += '      "   fireEvent.click(screen.getByText(\\\"Decrement\\\"));",\n';
code += '      "-  expect(screen.getByText(\\\"Count: 9\\\")).toBeInTheDocument();",\n';
code += '      "+  expect(screen.getByText(\\\"Count: 9\\\")).toBeDefined();",\n';
code += '      " });",\n';
code += '    ].join("\n"),\n';
code += '    explanation: "toBeInTheDocument requires testing-library/jest-dom. Replaced with toBeDefined.",\n';
code += '  },\n';
code += '};\n';

// Generate mock logs function using simple string arrays
code += '\n';
code += 'function generateMockLogs(errorType: ErrorType): string {\n';
code += '  switch (errorType) {\n';
code += '    case "lint":\n';
code += '      return [\n';
code += '        "$ npx eslint src/",\n';
code += '        "/app/src/utils/format.ts:18:10  error  Multiple spaces  no-multi-spaces",\n';
code += '        "\u2716 2 problems (2 errors, 0 warnings)"\n';
code += '      ].join("\n");\n';
code += '    case "type_error":\n';
code += '      return [\n';
code += '        "$ npx tsc --noEmit",\n';
code += '        "src/services/api.ts:45:3 - error TS2322: Type is not assignable",\n';
code += '        "Found 1 error."\n';
code += '      ].join("\n");\n';
code += '    case "failing_test":\n';
code += '      return [\n';
code += '        "$ npx jest --ci",\n';
code += '        "FAIL  src/components/Counter.test.tsx",\n';
code += '        "expect(element).toBeInTheDocument() - not implemented",\n';
code += '        "Tests: 1 failed, 2 passed (3 total)"\n';
code += '      ].join("\n");\n';
code += '  }\n';
code += '}\n';

code += '\n';
code += 'async function stageSandbox(jobId: string): Promise<void> {\n';
code += '  addStage(jobId, { name: "sandboxing", status: "running", details: "Initializing sandbox environment..." });\n';
code += '  const job = getJob(jobId);\n';
code += '  if (!job) return;\n';
code += '  const si = job.stages.length - 1;\n';
code += '  await sleep(800);\n';
code += '  const live = !!process.env.E2B_API_KEY;\n';
code += '  updateStage(jobId, si, {\n';
code += '    status: "completed",\n';
code += '    details: live\n';
code += '      ? "Sandbox ready (E2B). Repo cloned."\n';
code += '      : "Sandbox simulated: In-memory clone."\n';
code += '  });\n';
code += '}\n';

code += '\n';
code += 'async function stageDiagnose(jobId: string): Promise<ErrorType> {\n';
code += '  const job = getJob(jobId);\n';
code += '  if (!job) throw new Error("Job not found");\n';
code += '  addStage(jobId, { name: "diagnosing", status: "running", details: "Parsing CI logs..." });\n';
code += '  const u = getJob(jobId);\n';
code += '  if (!u) throw new Error("Job vanished");\n';
code += '  const si = u.stages.length - 1;\n';
code += '  await sleep(1000);\n';
code += '  const et = job.errorType || "lint";\n';
code += '  const logs = job.errorLog || generateMockLogs(et);\n';
code += '  updateStage(jobId, si, {\n';
code += '    status: "completed",\n';
code += '    details: "Diagnosis: " + et + ". Logs: " + logs.slice(0, 200)\n';
code += '  });\n';
code += '  return et;\n';
code += '}\n';

code += '\n';
code += 'async function stagePatch(jobId: string, et: ErrorType): Promise<void> {\n';
code += '  addStage(jobId, { name: "patching", status: "running", details: "Generating fix..." });\n';
code += '  const job = getJob(jobId);\n';
code += '  if (!job) return;\n';
code += '  const si = job.stages.length - 1;\n';
code += '  await sleep(1200);\n';
code += '  const hasLLM = !!(process.env.LLM_API_KEY || process.env.GEMINI_API_KEY);\n';
code += '  if (hasLLM) {\n';
code += '    updateStage(jobId, si, { status: "completed", details: "LLM fix received." });\n';
code += '  } else {\n';
code += '    const c = CANNED_DIFFS[et];\n';
code += '    setDiff(jobId, c.diff);\n';
code += '    updateStage(jobId, si, { status: "completed", details: c.explanation });\n';
code += '  }\n';
code += '}\n';

code += '\n';
code += 'async function stageVerify(jobId: string): Promise<boolean> {\n';
code += '  addStage(jobId, { name: "verifying", status: "running", details: "Running tests..." });\n';
code += '  const job = getJob(jobId);\n';
code += '  if (!job) return false;\n';
code += '  const si = job.stages.length - 1;\n';
code += '  await sleep(1500);\n';
code += '  const failChance = job.fixAttempts * 0.1;\n';
code += '
